site_name: Informatika
repo_url: https://github.com/chabErch/Informatika
site_author: chaberch
copyright: Copyright &copy; 2022 chaberch

theme:
  name: material
  custom_dir: overrides
  font:
    text: Lato
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

nav:
  - План проведения: '0. План.md'
  - Системы счисления:
    - Системы счисления: '1. Системы счисления/0. Системы счисления.md'
    - Единичная: '1. Системы счисления/1. Единичная.md'
    - Десятичная: '1. Системы счисления/2. Десятичная.md'
    - Двоичная: '1. Системы счисления/3. Двоичная.md'
    - Шестнадцатеричная: '1. Системы счисления/4. Шестнадцатеричная.md'
  - Сигналы:
    - Сигналы: '2. Сигналы/0. Сигналы.md'
    - Аналоговый: '2. Сигналы/1. Аналоговый.md'
    - Дискретный: '2. Сигналы/2. Дискретный.md'
    - Цифровой: '2. Сигналы/3. Цифровой.md'
  - Кодирование информации:
    - Кодирование информации: '3. Кодирование информации/0. Кодирование информации.md'
    - Текстовая:
      - Текстовая: '3. Кодирование информации/1. Текстовая/0. Текстовая.md'
      - Таблица ASCII: '3. Кодирование информации/1. Текстовая/1. ASCII.md'
      - Кириллическое расширение ASCII: '3. Кодирование информации/1. Текстовая/2. Кириллическое расширение ASCII.md'
      - Unicode: '3. Кодирование информации/1. Текстовая/3. Unicode.md'
  - Хранение информации:
    - Оптические диски: '4. Хранение информации/1. Оптические диски.md'
    - Жесткие диски: '4. Хранение информации/2. Жесткие диски.md'
  - Что такое Интернет:
    - История сети Интернет: '5. Что такое интернет/0. История Интернета.md'
    - Построение сети: '5. Что такое интернет/1. Построение сети.md'
    - Интернет-провайдеры: '5. Что такое интернет/2. Провайдеры.md'
    - Протоколы передачи данных: '5. Что такое интернет/3. Протоколы.md'
    - МАС адрес: '5. Что такое интернет/4. MAC.md'
  - Безопасность в Интернете:
    - Вредоносные программы: '6. Безопасность в интернете/0. Вредоносные программы.md'
    - Безопасность аккаунтов: '6. Безопасность в интернете/1. Безопасность аккаунтов.md'
    
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/chabErch
      name: ChabErch
    - icon: fontawesome/brands/github 
      link: https://github.com/userusr
      name: userusr
      
extra_css:
  - stylesheets/extra.css
      
    
markdown_extensions:
  - footnotes
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: ru
  - print-site:
      add_cover_page: true
      cover_page_template: "custom_cover_page.tpl"
  - git-revision-date-localized:
      enable_creation_date: true