site_name: Informatika

theme:
  name: material
  
nav:
  - План проведения: 'План.md'
  - Системы счисления: 'Системы счисления.md'
  - Цифровой и аналоговый сигналы: 'Цифра и аналог.md'
  - 'Кодирование текстовой информации': 
    - Общие сведения: 'Кодирование текстовой информации/Общие сведения.md'
    - Таблица ASCII: 'Кодирование текстовой информации/ASCII.md'
    - Кириллическое расширение ASCII: 'Кодирование текстовой информации/Кириллическое расширение ASCII.md'
  - 'Хранение информации':
    - Оптические диски: 'Хранение информации/Оптические диски.md'
    - Жесткие диски: 'Хранение информации/Жесткие диски.md'
  - 'Что такое Интернет':
    - История сети Интернет: 'Что такое интернет/История Интернета.md'
    - Построение сети: 'Что такое интернет/Построение сети.md'
    - Интернет-провайдеры: 'Что такое интернет/Провайдеры.md'
    - Протоколы передачи данных: 'Что такое интернет/Протоколы.md'
    - МАС адрес: 'Что такое интернет/MAC.md'
  - 'Безопасность в Интернете':
    - Вредоносные программы: 'Безопасность в интернете/Вредоносные программы.md'
    - Безопасность аккаунтов: 'Безопасность в интернете/Безопасность аккаунтов.md'
    
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/chabErch
      name: ChabErch
    - icon: fontawesome/brands/github 
      link: https://github.com/userusr
      name: userusr
      
markdown_extensions:
  - footnotes
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: ru
  - print-site:
      add_print_site_banner: true
