site_name: Informatika
theme:
  name: material
nav:
    - План проведения: 'План.md'
    - История сети Интернет: 'История Интернета.md'
    - Построение сети: 'Построение сети.md'
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/chabErch
      name: ChabErch
    - icon: fontawesome/brands/github 
      link: https://github.com/userusr
      name: userusr
markdown_extensions:
    - footnotes
    - abbr
    - pymdownx.snippets
    - attr_list
    - md_in_html
