site_name: Informatika
repo_url: https://github.com/chabErch/Informatika
site_author: chaberch
copyright: Copyright &copy; 2022 chaberch

theme:
  name: material
  custom_dir: overrides
  font:
    text: Lato
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
        


  
nav:
  - План проведения: 'План.md'
  - Системы счисления:
    - Системы счисления: 'Системы счисления/Системы счисления.md'
    - Единичная: 'Системы счисления/Единичная.md'
    - Десятичная: 'Системы счисления/Десятичная.md'
    - Двоичная: 'Системы счисления/Двоичная.md'
    - Шестнадцатеричная: 'Системы счисления/Шестнадцатеричная.md'
  - Сигналы:
    - Сигналы: 'Сигналы/Сигналы.md'
    - Аналоговый: 'Сигналы/Аналоговый.md'
    - Дискретный: 'Сигналы/Дискретный.md'
    - Цифровой: 'Сигналы/Цифровой.md'
  - Кодирование текстовой информации: 
    - Общие сведения: 'Кодирование текстовой информации/Общие сведения.md'
    - Таблица ASCII: 'Кодирование текстовой информации/ASCII.md'
    - Кириллическое расширение ASCII: 'Кодирование текстовой информации/Кириллическое расширение ASCII.md'
    - Unicode: 'Кодирование текстовой информации/Unicode.md'
  - Хранение информации:
    - Оптические диски: 'Хранение информации/Оптические диски.md'
    - Жесткие диски: 'Хранение информации/Жесткие диски.md'
  - Что такое Интернет:
    - История сети Интернет: 'Что такое интернет/История Интернета.md'
    - Построение сети: 'Что такое интернет/Построение сети.md'
    - Интернет-провайдеры: 'Что такое интернет/Провайдеры.md'
    - Протоколы передачи данных: 'Что такое интернет/Протоколы.md'
    - МАС адрес: 'Что такое интернет/MAC.md'
  - Безопасность в Интернете:
    - Вредоносные программы: 'Безопасность в интернете/Вредоносные программы.md'
    - Безопасность аккаунтов: 'Безопасность в интернете/Безопасность аккаунтов.md'
    
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/chabErch
      name: ChabErch
    - icon: fontawesome/brands/github 
      link: https://github.com/userusr
      name: userusr
      
extra_css:
  - stylesheets/extra.css
      
    
markdown_extensions:
  - footnotes
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: ru
  - print-site:
      add_cover_page: true
      cover_page_template: "custom_cover_page.tpl"
  - git-revision-date-localized:
      enable_creation_date: true